language: php
php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update
  - composer --version

install:
  - Build/Test/bootstrap.sh

script:
  - Build/Test/cibuild.sh

cache:
  directories:
    - $HOME/.composer/cache
